// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0-devel
// 	protoc        v3.9.0
// source: training.proto

package training

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_training_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{0}
}

type HogeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *HogeResponse) Reset() {
	*x = HogeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_training_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HogeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HogeResponse) ProtoMessage() {}

func (x *HogeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HogeResponse.ProtoReflect.Descriptor instead.
func (*HogeResponse) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{1}
}

func (x *HogeResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

var File_training_proto protoreflect.FileDescriptor

var file_training_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x2a, 0x0a, 0x0c, 0x48, 0x6f, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x32,
	0x3d, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x31, 0x0a, 0x04, 0x48,
	0x6f, 0x67, 0x65, 0x12, 0x0f, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x2e,
	0x48, 0x6f, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_training_proto_rawDescOnce sync.Once
	file_training_proto_rawDescData = file_training_proto_rawDesc
)

func file_training_proto_rawDescGZIP() []byte {
	file_training_proto_rawDescOnce.Do(func() {
		file_training_proto_rawDescData = protoimpl.X.CompressGZIP(file_training_proto_rawDescData)
	})
	return file_training_proto_rawDescData
}

var file_training_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_training_proto_goTypes = []interface{}{
	(*Empty)(nil),        // 0: training.Empty
	(*HogeResponse)(nil), // 1: training.HogeResponse
}
var file_training_proto_depIdxs = []int32{
	0, // 0: training.Training.Hoge:input_type -> training.Empty
	1, // 1: training.Training.Hoge:output_type -> training.HogeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_training_proto_init() }
func file_training_proto_init() {
	if File_training_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_training_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_training_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HogeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_training_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_training_proto_goTypes,
		DependencyIndexes: file_training_proto_depIdxs,
		MessageInfos:      file_training_proto_msgTypes,
	}.Build()
	File_training_proto = out.File
	file_training_proto_rawDesc = nil
	file_training_proto_goTypes = nil
	file_training_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TrainingClient is the client API for Training service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TrainingClient interface {
	Hoge(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HogeResponse, error)
}

type trainingClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainingClient(cc grpc.ClientConnInterface) TrainingClient {
	return &trainingClient{cc}
}

func (c *trainingClient) Hoge(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HogeResponse, error) {
	out := new(HogeResponse)
	err := c.cc.Invoke(ctx, "/training.Training/Hoge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrainingServer is the server API for Training service.
type TrainingServer interface {
	Hoge(context.Context, *Empty) (*HogeResponse, error)
}

// UnimplementedTrainingServer can be embedded to have forward compatible implementations.
type UnimplementedTrainingServer struct {
}

func (*UnimplementedTrainingServer) Hoge(context.Context, *Empty) (*HogeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hoge not implemented")
}

func RegisterTrainingServer(s *grpc.Server, srv TrainingServer) {
	s.RegisterService(&_Training_serviceDesc, srv)
}

func _Training_Hoge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingServer).Hoge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/training.Training/Hoge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingServer).Hoge(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Training_serviceDesc = grpc.ServiceDesc{
	ServiceName: "training.Training",
	HandlerType: (*TrainingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hoge",
			Handler:    _Training_Hoge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "training.proto",
}
